#!/usr/bin/env bash

# Bash script that allows for easy interfacing with docker containers.

ENTRY_POINT=${1};
DOCKER_CONTAINER_PREFIX=$(basename "`pwd`");
USER_ARGS=${@:2}

if ! echo "dotnet psql npm node" | tr " " '\n' | grep -F -q -x ${ENTRY_POINT} 2>/dev/null; then
    echo "Invalid command! Please pick between [dotnet, psql, npm, node]."
    exit 1;
elif [ ${ENTRY_POINT} == "dotnet" ]; then
    docker exec -it "${DOCKER_CONTAINER_PREFIX}-api-1" dotnet ${USER_ARGS}
elif [ ${ENTRY_POINT} == "psql" ]; then
    docker exec -it "${DOCKER_CONTAINER_PREFIX}-database-1" psql -U lms -d lms ${USER_ARGS}
elif [ ${ENTRY_POINT} == "npm" ]; then
    docker exec -it "${DOCKER_CONTAINER_PREFIX}-web-1" npm ${USER_ARGS}
elif [ ${ENTRY_POINT} == "node" ]; then
    docker exec -it "${DOCKER_CONTAINER_PREFIX}-web-1" node ${USER_ARGS}
fi
